apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --out k8s/
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: babu-rao-ganpatrao-bank-service
  name: babu-rao-ganpatrao-bank-service
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3000
  selector:
    io.kompose.service: babu-rao-ganpatrao-bank-service
