apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: babu-rao-ganpatrao-bank-redis-data
  name: babu-rao-ganpatrao-bank-redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
