apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: chinta-mat-karo-redis-data
  name: chinta-mat-karo-redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
