apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --out k8s/
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml --out k8s/
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: kafka
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_JVM_PERFORMANCE_OPTS
              value: -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:+ExplicitGCInvokesConcurrent -Djava.awt.headless=true -Dlog4j.configuration=file:/opt/confluent/etc/kafka/log4j.properties
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092
            - name: KAFKA_LOG4J_LOGGERS
              value: kafka=OFF,org.apache.kafka=OFF,kafka.coordinator.group.GroupMetadataManager=OFF,state.change.logger=OFF,kafka.log.LogCleaner=OFF,kafka.controller=OFF,kafka.server.KafkaApis=OFF,kafka.network.RequestChannel=OFF,kafka.cluster.Partition=OFF,kafka.log.Log=OFF,kafka.log.LogSegment=OFF,kafka.utils.Log4jController=OFF
            - name: KAFKA_LOG4J_ROOT_LOGLEVEL
              value: "OFF"
            - name: KAFKA_LOG_MESSAGE_FORMAT_VERSION
              value: "2.8"
            - name: KAFKA_LOG_MESSAGE_TIMESTAMP_TYPE
              value: CreateTime
            - name: KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS
              value: "300000"
            - name: KAFKA_LOG_RETENTION_HOURS
              value: "168"
            - name: KAFKA_LOG_SEGMENT_BYTES
              value: "1073741824"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TOOLS_LOG4J_LOGLEVEL
              value: "OFF"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          image: confluentinc/cp-kafka:6.2.0
          livenessProbe:
            exec:
              command:
                - kafka-topics --bootstrap-server kafka:9092 --list || exit 1
            failureThreshold: 10
            periodSeconds: 10
            timeoutSeconds: 5
          name: kafka
      restartPolicy: Always
