apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --out k8s/
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: nth-switch
  name: nth-switch
spec:
  ports:
    - name: "3005"
      port: 3005
      targetPort: 3000
  selector:
    io.kompose.service: nth-switch
