apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: paisa-vasool-bank-redis-data
  name: paisa-vasool-bank-redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
